### ISSUE TITLE
Is `minlp_solver` a required field? 

### ISSUE THREAD

**Issue by Vaibhavdixit02** [lanl-ansi/Alpine.jl#232]
**Describe the bug**
The title is basically it, is it a required field? The examples don't seem to have it in the `run_examples.jl` file but I got an error when trying to use it from the MOI interface

**Comment by harshangrjn** [comment]
`minlp_solver` is necessary only when your original nonlinear problem has binary variables. For example, to run [this](https://github.com/lanl-ansi/Alpine.jl/blob/32757b2568acfe71257e41ed4122a120717a6460/examples/MINLPs/blend.jl#LL1C1-L1C1) instance, just uncomment the `minlp_solver` option in [here](https://github.com/lanl-ansi/Alpine.jl/blob/32757b2568acfe71257e41ed4122a120717a6460/examples/run_examples.jl#L32) and it should work. This line was commented out because the example `nlp3` has only continuous variables.

**Comment by Vaibhavdixit02** [comment]
Thanks for the clarification
