### ISSUE TITLE
Replacing variables with constants

### ISSUE THREAD

**Issue by rb004f** [lanl-ansi/Alpine.jl#57]
in discussions with @jac0320 we noticed that in some cases bound tightening reduced variables to constants. To improve performance, we could replace variables with constants.

Suggested architecture: We can use our relaxation pattern matching architecture that already replaces constraints with their relaxation. In this case we look for any constraint that has a variable whose ub = lb, and replace that constraint with the "relaxed constraint" where that variable is replaced with a constant

**Comment by jac0320** [comment]
Another comment: directly doing this is not as easy as it seems. As the model is parsed into MPB for upper bound search, deleting a variable is not easy since the abstraction layer is fairly raw. But this definitely motivates a different design of data structure which has more control of the raw model data.

**Comment by kaarthiksundar** [comment]
Can lead to numerical issues. Leave the onus on the user to remove redundancies.
