### ISSUE TITLE
Piecewise quadratic relaxations 

### ISSUE THREAD

**Issue by harshangrjn** [lanl-ansi/Alpine.jl#88]
Can you confirm, for the piecewise relaxation of the quadratic term in POD, is formulation (5) of https://arxiv.org/pdf/1707.02514.pdf implemented? From function "amp_post_tmc_monomial_mc" it looks like (5) is implemented. If so, the additional cuts we derived on \hat{Y} matrix can be added to strengthen the formulation.

**Comment by harshangrjn** [comment]
@kaarthiksundar?

**Comment by kaarthiksundar** [comment]
You are correct - that is what is implemented.

**Comment by harshangrjn** [comment]
Then what about the additional cuts on Y-hat matrix?

**Comment by kaarthiksundar** [comment]
Not in priority list for now. I will may be get to it early next year. For now, this I am trying to get done before year end are getting POD to work in Julia 0.7 and Julia 1.0 and then rewriting tests and some general code clean up. This will take at least 2-3 months. Feel free to add the cuts and submit a PR, if you want them implemented asap.

**Comment by kaarthiksundar** [comment]
@harshangrjn  Have no plans from my side to implement and test this. Let me know if you are planning on doing this. Otherwise we can close this issue.

**Comment by harshangrjn** [comment]
Let this stay open until we finalize the best formulation.

**Comment by krishpat** [comment]
@harshangrjn Is there a paper where you have these cuts on \hat{Y} matrix explained? I can try to implement them and test.

**Comment by harshangrjn** [comment]
@krishpat Not really! They are simple cuts on the space of lifted variables. I can type them up and share it soon.

**Comment by kaarthiksundar** [comment]
@harshangrjn If you look more closely in Eq (5) of https://arxiv.org/pdf/1707.02514.pdf, you will see that no \hat{Y} matrix is needed. In fact Eq. (5) is exactly what is implemented without the \hat{Y} matrix since Eq (5) is already linear. No additional binary variables required. It is needed only for the Piecewise McCormick constraints and not in the piecewise quadratic relaxations, in which case we already know it does not work well when compared to the formulation that is implemented. 

The sentences in the paper below Eq (5) is not needed - it is a typo in the paper.

**Comment by harshangrjn** [comment]
Yes! Unlike piecewise McCormick formulation, the piecewise quadratic relaxation doesn't require a lifted variable matrix. Thanks to @krishpat for re-initiating this thread as it can be closed now. 

Btw, its not really a typo in the paper as the formulation and linearization are still right. Except that the lifted variable matrix variables are not binary and instead belong to [0,1]. Since anyway one of the variables in the product is always zero, the relaxation is still exact. Though I agree its not compact.
